ci(track): bump upload-charm action 2.4.0 -> 2.6.2
canonical/dex-auth-operator pull request #207
Opened 2024-07-11 07:51 UTC by orfeas-k

Ref canonical/bundle-kubeflow#962

2024-07-12 20:15 UTC, DnPlas requested changes

2024-07-12 20:15 UTC, DnPlas commented on .github/workflows/publish.yaml
Let's also bump the release job

2024-07-15 08:59 UTC, misohu commented on .github/workflows/publish.yaml
We agreed that the release job did not update so this is not needed. Check jira for more info.

2024-07-15 08:59 UTC, misohu approved these changes
Good job :)

2024-07-15 11:45 UTC, merged